# Dependabot configuration file
version: 2  # Use version 2

# List of update configs
updates:
  # Configuration for npm package ecosystem
  - package-ecosystem: "npm"  
    directory: "/"  # Root directory
    schedule:
      interval: "daily"  # Update frequency

  # Configuration for Docker package ecosystem
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # Configuration for GitHub Actions package ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
